"""
Output — Module 8 of the ReGenAI pipeline.

Takes ProjectSummary objects from Module 7 and writes structured
markdown files to the output directory. One directory and one .md
file per project or topic.
"""

import re
from pathlib import Path

from rich.console import Console

from regenai.raptor import ProjectSummary

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _sanitize_dirname(name: str) -> str:
    """Convert a project name to a safe directory name."""
    # Replace spaces and special chars with underscores
    safe = re.sub(r"[^\w\-]", "_", name)
    # Collapse multiple underscores
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe or "unnamed"


def _build_markdown(summary: ProjectSummary) -> str:
    """Build the markdown content for a single project/topic."""
    lines: list[str] = []

    # Title
    lines.append(f"# {summary.project_name}")
    lines.append("")

    # Metadata
    if summary.project_root:
        lines.append(f"**Project Root:** `{summary.project_root}`")
    else:
        lines.append(
            "**Type:** Unanchored topic (files not belonging to a specific project)"
        )

    lines.append(f"**Confidence Score:** {summary.avg_confidence:.2f}")
    lines.append(f"**Files Analyzed:** {len(summary.source_files)}")
    lines.append("")

    # Summary
    lines.append("---")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(summary.project_summary)
    lines.append("")

    # Source files
    lines.append("---")
    lines.append("")
    lines.append("## Source Files")
    lines.append("")
    for filepath in summary.source_files:
        lines.append(f"- `{filepath}`")
    lines.append("")

    # Cluster summaries (if multiple clusters contributed)
    if len(summary.cluster_summaries) > 1:
        lines.append("---")
        lines.append("")
        lines.append("## Detailed Cluster Summaries")
        lines.append("")
        for i, cs in enumerate(summary.cluster_summaries, 1):
            lines.append(f"### Cluster {i}")
            lines.append("")
            lines.append(cs)
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by ReGenAI*")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main output generator
# ---------------------------------------------------------------------------


def write_output(
    project_summaries: list[ProjectSummary],
    output_dir: Path,
) -> None:
    """
    Write markdown files for all project summaries.

    Creates one directory per project/topic with a .md file inside.

    Args:
        project_summaries: Output from Module 7 (raptor).
        output_dir: Root output directory.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    written: list[tuple[str, Path]] = []

    for summary in project_summaries:
        # Create project directory
        dirname = _sanitize_dirname(summary.project_name)
        project_dir = output_dir / dirname
        project_dir.mkdir(parents=True, exist_ok=True)

        # Write markdown
        md_content = _build_markdown(summary)
        md_path = project_dir / f"{dirname}.md"
        md_path.write_text(md_content, encoding="utf-8")

        written.append((summary.project_name, md_path))

    # Print results
    console.print(f"  [green]Written {len(written)} project summaries:[/green]")
    for name, path in written:
        console.print(f"    📄 {path}")
    console.print()
